package com.example.duhongwang20180601.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.duhongwang20180601.bean.SearchDaoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_DAO_BEAN".
*/
public class SearchDaoBeanDao extends AbstractDao<SearchDaoBean, Long> {

    public static final String TABLENAME = "SEARCH_DAO_BEAN";

    /**
     * Properties of entity SearchDaoBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uid = new Property(1, String.class, "uid", false, "UID");
        public final static Property Uname = new Property(2, String.class, "uname", false, "UNAME");
        public final static Property SelectGoods = new Property(3, String.class, "selectGoods", false, "SELECT_GOODS");
    }


    public SearchDaoBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SearchDaoBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_DAO_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UID\" TEXT," + // 1: uid
                "\"UNAME\" TEXT," + // 2: uname
                "\"SELECT_GOODS\" TEXT);"); // 3: selectGoods
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_DAO_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SearchDaoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(2, uid);
        }
 
        String uname = entity.getUname();
        if (uname != null) {
            stmt.bindString(3, uname);
        }
 
        String selectGoods = entity.getSelectGoods();
        if (selectGoods != null) {
            stmt.bindString(4, selectGoods);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SearchDaoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(2, uid);
        }
 
        String uname = entity.getUname();
        if (uname != null) {
            stmt.bindString(3, uname);
        }
 
        String selectGoods = entity.getSelectGoods();
        if (selectGoods != null) {
            stmt.bindString(4, selectGoods);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SearchDaoBean readEntity(Cursor cursor, int offset) {
        SearchDaoBean entity = new SearchDaoBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // uname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // selectGoods
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SearchDaoBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSelectGoods(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SearchDaoBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SearchDaoBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SearchDaoBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
